#+title: Courses for Fall 2022
* Fall 2022
** Useful links
*** MyCourses
https://mycourses2.mcgill.ca/d2l/home/411454
*** Minerva
https://horizon.mcgill.ca/pban1/twbkwbis.P_WWWLogin
*** McGill Email
https://outlook.office.com/owa/mcgill.ca
*** McGill Library Room Bookings
https://libraryrooms.mcgill.ca/reserve/groupstudy
*** Get ready
https://www.mcgill.ca/getready/

** Mila
***
** Research

*** Scrum meeting - 07/Sep/2022
**** Updates
***** Enrolled in COMP 599 - Natural language understanding with Siva Reddy
***** Mila access card acquired
**** Other things
***** 

**** 
*** Catch up with Jackie - 02/Sep/2022
**** Updates
***** Enrolled in:
Comp 551 (Applied Machine Learning) +
Comp 547 (Encryption)
***** Waitlisted for:
Comp 585 (Intelligent Software systems)
Will drop 547 if I get into 585 after week 2.
The lecturer seems optimistic people will drop out.
***** Submitted for desk at Mila
**** Agenda
***** How to get started
***** Letter of Understanding
Resource here:
https://www.mcgill.ca/gradcsupervision/resources/examples-templates-and-tools
***** Speaking invitations
****** Indigenous AI Summit
Indigenous Innovation, Data Economies and Artificial Intelligence
Summit (IDEAS) event
Date: Friday 31st March 2023
Location: Arizona State University in Scottsdale, AZ
****** NeurIPS 2022
Indigenous in AI - attending in person
**** Action points
** Funding
*** Apply for graduate funding

    All Doctoral students are required to apply for at least one federal and one provincial award each year they are eligible. GPS has launched a pilot initiative to provide a French abstract review service for FRQ doctoral fellowship applications. In order to benefit from the service, applicants must submit a draft translation of their project summary (lay abstract) in French.
    The service is offered to:

        All FRQSC doctoral applicants
        100 FRQNT doctoral applicants (first come, first served)
        100 FRQS doctoral applicants (first come, first served)

    Translation upload requirements:

        Title (max 400 characters)
        Lay abstract (max 500 words)
            In order to benefit form the translation review service offered by GPS, students must submit their English abstract and a draft French translation.
            Applicants must use DeepL or Reverso (not Google Translate) for their initial translation and indicate which one they used. 
        Each abstract must include the student’s full name and e-mail address.

    A single .doc or .docx file must be submitted to GPS through the webform by September 15, 2022. The file must be renamed to AGENCY_StudentName (e.g.: FRQS_JohnDoe).

    In order to maximize their chances, students are encouraged to consult FRQ information session materials on this page (including Tips & Tricks for successful Fellowship applications). Consult the attachment for more information.

    As a reminder, competition deadlines for final submission vary by agency:

        FRQNT Doctoral Award – October 4 at 4:00 PM
        FRQS Doctoral Award– October 6 at 4:00 PM
        FRQSC Doctoral Award – October 12 at 4:00 PM 
** Comp 551 - Applied Machine Learning
*** Useful links
**** Course website
https://www.cs.mcgill.ca/~yueli/teaching/COMP551_Fall2022/comp551_syllabus.html
****
*** Lecture 4 - 13/Sep/2022
**** True/False positive rates
***** True positive rate = True positives / Positives = TP / (TP + FN)
***** Classification models can produce probabilities
***** Setting thresholds for FP/FN rates
***** ROC Curves
*** Lecture 3 - 8/Sep/2022
**** More KNN on Iris dataset
***** Talked about:
****** Colab notebook example code
****** Emphasising how to implement train/validation/test split
****** Will go through example slowly in tutorial?
****** Computational complexity
****** Feature scale sensitivity/Feature standardization
****** Weighted kNN
****** Concentration of measure/Curse of dimensionality
**** Core ML Concepts
***** Model evaluation
***** Model selection
***** ROC Curve
***** Cross-validation
***** Method comparison

*** Lecture 2 - 6/Sep/2022
K Nearest Neighbours
**** 
*** Lecture 1 - 1/Sep/2022
**** Course Evaluation
Weekly online quizzes - 10%
One written midterm examination - 35%
Mini-project 1 - 9%
Mini-project 2 - 12%
Mini-project 3 - 17%
Mini-project 4 - 17%
**** Things to look into:
***** Ed Discussion
***** MyCourses
***** Google Colab setup
**** Topics covered
***** Objectives
***** Course overview
***** Key course information
***** What is machine learning?
***** Supervised Learning
***** Unsupervised learning
***** Semisupervised learning
***** Reinforcement learning (not covered in this course)
** Comp 599 - Natural Language Understanding
*** Lecture 4 - 13/Sep/2022
**** 

