#+title: Kaupapa doc

* Ohu Raraunga
** Māori Data Governance Model report
*** DONE Algorithms sub-section
CLOSED: [2022-09-10 Sat 08:16]
2 paras
Also can you think of an example (bad) or exemplar (positive)
I can write that up if you point me in the right direction with url
or material
*** DONE Data linkage and integration sub-section
CLOSED: [2022-09-10 Sat 08:05]
2 paras please
pull-out example using Equity Index from your chapter in Counting zeroes
*** DONE Finish section on Te Pu a nga Maara
CLOSED: [2022-09-02 Fri 14:51]
*** DONE Second paragraph for 2.2 on Distributed and Decentralised
CLOSED: [2022-09-09 Fri 14:21]
and few sentences at the top of the context setting para
** Hui 5/Sep/2022
*** Kylie Reiri said to consider specific technology solutions
*** NZ Govt agencies standing up Māori Data Governance rōpū
They don't know what they're trying to govern, it has to be explained
to them.
*** System-wide governance as opposed to fine-grain details
*** Thoughts from Aroha
The policy is about the principle of active protection because it is a
taonga
It's not for the kawanatanga to define what it is or how Māori use data.
It's up to them to make sure the protocols are in place for access and
return to Māori
*** What is the operating model?
Whose job is it to open the door when Māori come knocking?
Technological considerations for sharing information
(NB: sharing with Māori vs sharing with public/transparency have different
technical requirements)
*** 
* Side-projects

** Spanning tree dictionary-derived dataset
Idea: Derive an ordering on the language vocabulary that maximises the information gain for language learners
using an external source (such as a dictionary or a text corpus)

* Indigenous in AI
** TODO Send details to Lauren Halley
** TODO Confirm attendance at NeurIPS 2022

